export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const USER_ADD = "USER_ADD";
export const USER_UPDATE = "USER_UPDATE";
export const USER_DELETE = "USER_DELETE";
export const USER_GET = "USER_GET";

export const BATTERY_GET = "BATTERY_GET";
export const BATTERY_ADD = "BATTERY_ADD";
export const BATTERY_UPDATE = "BATTERY_UPDATE";
export const BATTERY_DELETE = "BATTERY_DELETE";
export const BATTERY_LOADING = "BATTERY_LOADING";

export const ELECTRONIC_GET = "ELECTRONIC_GET";
export const ELECTRONIC_ADD = "ELECTRONIC_ADD";
export const ELECTRONIC_UPDATE = "ELECTRONIC_UPDATE";
export const ELECTRONIC_DELETE = "ELECTRONIC_DELETE";

export const OIL_GET = "OIL_GET";
export const OIL_ADD = "OIL_ADD";
export const OIL_UPDATE = "OIL_UPDATE";
export const OIL_DELETE = "OIL_DELETE";

export const REVIEW_GET = "REVIEW_GET";
export const REVIEW_ADD = "REVIEW_ADD";
export const REVIEW_UPDATE = "REVIEW_UPDATE";
export const REVIEW_DELETE = "REVIEW_DELETE";
export const REVIEW_DETAIL_ADD = "REVIEW_DETAIL_ADD";
export const REVIEW_DETAIL_UPDATE = "REVIEW_DETAIL_UPDATE";
export const REVIEW_DETAIL_DELETE = "REVIEW_DETAIL_DELETE";

export const HIGHLIGHT_GET = "HIGHLIGHT_GET";
export const HIGHLIGHT_ADD = "HIGHLIGHT_ADD";
export const HIGHLIGHT_UPDATE = "HIGHLIGHT_UPDATE";
export const HIGHLIGHT_DELETE = "HIGHLIGHT_DELETE";
export const HIGHLIGHT_DETAIL_ADD = "HIGHLIGHT_DETAIL_ADD";
export const HIGHLIGHT_DETAIL_UPDATE = "HIGHLIGHT_DETAIL_UPDATE";
export const HIGHLIGHT_DETAIL_DELETE = "HIGHLIGHT_DETAIL_DELETE";

export const QUOTE_GET = "QUOTE_GET";
export const QUOTE_ADD = "QUOTE_ADD";
export const QUOTE_UPDATE = "QUOTE_UPDATE";
export const QUOTE_DELETE = "QUOTE_DELETE";

export const CAR_GET = "CAR_GET";
export const CAR_ADD = "CAR_ADD";
export const CAR_UPDATE = "CAR_UPDATE";
export const CAR_DELETE = "CAR_DELETE";
export const CAR_MODEL_ADD = "CAR_MODEL_ADD";
export const CAR_MODEL_UPDATE = "CAR_MODEL_UPDATE";
export const CAR_MODEL_DELETE = "CAR_MODEL_DELETE";
export const CAR_YEAR_ADD = "CAR_YEAR_ADD";
export const CAR_YEAR_UPDATE = "CAR_YEAR_UPDATE";
export const CAR_YEAR_DELETE = "CAR_YEAR_DELETE";
export const CAR_CYLINDER_ADD = "CAR_CYLINDER_ADD";
export const CAR_CYLINDER_UPDATE = "CAR_CYLINDER_UPDATE";
export const CAR_CYLINDER_DELETE = "CAR_CYLINDER_DELETE";

export const SERVICE_GET = "SERVICE_GET";
export const SERVICE_ADD = "SERVICE_ADD";
export const SERVICE_UPDATE = "SERVICE_UPDATE";
export const SERVICE_DELETE = "SERVICE_DELETE";
export const SERVICE_DATA_ADD = "SERVICE_DATA_ADD";
export const SERVICE_DATA_UPDATE = "SERVICE_DATA_UPDATE";
export const SERVICE_DATA_DELETE = "SERVICE_DATA_DELETE";
export const SERVICE_SUBDATA_ADD = "SERVICE_SUBDATA_ADD";
export const SERVICE_SUBDATA_UPDATE = "SERVICE_SUBDATA_UPDATE";
export const SERVICE_SUBDATA_DELETE = "SERVICE_SUBDATA_DELETE";
export const SERVICE_SERVICELIST_ADD = "SERVICE_SERVICELIST_ADD";
export const SERVICE_SERVICELIST_UPDATE = "SERVICE_SERVICELIST_UPDATE";
export const SERVICE_SERVICELIST_DELETE = "SERVICE_SERVICELIST_DELETE";